package:
  name: gippy
  version: 1.0.0

source:
  # https://github.com/gipit/gippy
  path: ../gippy-d7537453d1edd0262f9fd16e70dfb0b4c8d0cf35
requirements:
  build:
    - gcc
    - python
    - numpy 1.14.2
    - libgdal 2.2.4
    - wheel

  run:
    - python

build:
  string: py{{py}}_0
  binary_relocation: False

about:
  home: https://github.com/gipit/gippy
  summary: "Gippy is a Python library for image processing of geospatial raster data"
  license: Apache 2.0
