package:
  name: bfalg-ndwi
  version: 1.1.1

source:
  path: ../../vendor/bfalg-ndwi

requirements:
  build:
    - python 2.7.14
  run:
    - python 2.7.14
    - beachfront

build:
  preserve_egg_dir: True
  string: py{{py}}_0
  #binary_relocation: False

about:
  home: https://github.com/venicegeo/bfalg-ndwi
  summary: "A library and a CLI for running shoreline detection "
  license: Apache 2.0
