package:
  name: bfalg-ndwi
  version: x

source:
  path: ./bfalg-ndwi

requirements:
  build:
    - beachfront x
    - setuptools 39.2.0
    - numpy 1.14.0 py27_blas_openblas_200
    - python 2.7.13
    - gdal 2.1.3
  run:
    - beachfront x
    - numpy 1.14.0 py27_blas_openblas_200
    - python 2.7.13
    - gdal 2.1.3

build:
  preserve_egg_dir: True
  string: py{{py}}_0
  #binary_relocation: False

about:
  home: https://github.com/venicegeo/bfalg-ndwi
  summary: "A library and a CLI for running shoreline detection "
  license: Apache 2.0
