package:
  name: bfalg-ndwi
  version: 1.0.8

source:
  path: ../../vendor/bfalg-ndwi

requirements:
  build:
    - python 2.7.13
  run:
    - python 2.7.13
    - beachfront
    - numpy 1.12.0 py27_blas_openblas_200

build:
  preserve_egg_dir: True
  string: py{{py}}_0
  #binary_relocation: False

about:
  home: https://github.com/venicegeo/bfalg-ndwi
  summary: "A library and a CLI for running shoreline detection "
  license: Apache 2.0
