package:
  name: bfalg_wta
  version: 0.1.0

source:
  path: ../../vendor/bfalg_WTA
requirements:
  build:
    - gcc
    - numpy 1.12.0
    - gippy
    - beachfront
    - pypotrace
    - scikit-image 0.13.0
    - scikit-learn 0.18.1
    - scipy 0.19.0
    - pyproj 1.9.5.1
    - requests 2.11.1
    - fiona 1.7.4

  run:
    - numpy 1.12.0
    - gippy
    - beachfront
    - pypotrace
    - scikit-image 0.13.0
    - scikit-learn 0.18.1
    - scipy 0.19.0
    - pyproj 1.9.5.1
    - requests 2.11.1
    - fiona 1.7.4

build:
  preserve_egg_dir: True
  string: py{{py}}_0
  #binary_relocation: False

about:
  home: https://github.com/venicegeo/bfalg_wta
  summary: "A library and a CLI for running shoreline detection "
  license: Apache 2.0
