package:
  name: bfalg_wta
  version: 1.0.1

source:
  path: ../../vendor/bfalg_WTA
requirements:
  build:
    - gcc
    - beachfront
    - scikit-image 0.13.0
    - scikit-learn 0.18.1
    - scipy 0.19.0
    - six 1.10.0

  run:
    - beachfront
    - scikit-image 0.13.0
    - scikit-learn 0.18.1
    - scipy 0.19.0
    - six 1.10.0

build:
  preserve_egg_dir: True
  string: py{{py}}_0
  #binary_relocation: False

about:
  home: https://github.com/venicegeo/bfalg_wta
  summary: "A library and a CLI for running shoreline detection "
  license: Apache 2.0
