package:
  name: bfalg_wta
  version: 0.1.0

source:
  path: ../../vendor/bfalg_WTA
requirements:
  build:
    - gcc
    - python 2.7.13 
    - beachfront 0.2.1
    - scikit-image 0.13.0
    - scikit-learn 0.18.1
    - scipy 0.19.0
 #   - numpy 1.12.0 py27_blas_openblas_200

  run:
    - python 2.7.13 
    - beachfront 0.2.1
    - scikit-image 0.13.0
    - scikit-learn 0.18.1
    - scipy 0.19.0
#    - numpy 1.12.0 py27_blas_openblas_200

build:
  preserve_egg_dir: True
  string: py{{py}}_0
  #binary_relocation: False

about:
  home: https://github.com/venicegeo/bfalg_wta
  summary: "A library and a CLI for running shoreline detection "
  license: Apache 2.0
