language: python
python:
- '2.7'
- '3.3'
- pypy
env:
- CONDA_BLD_PATH=~/conda-bld
install:
  # The Conda + Travis FAQ recommends an apt-get update, but it errors.
  #- sudo apt-get update
  # Install Anaconda per https://gist.github.com/zshaheen/fe76d1507839ed6fbfbccef6b9c13ed9
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda update -q conda
  - conda info -a
  - conda install conda-build anaconda-client
  - conda build recipes/libagg
  - conda install libagg --use-local
  - conda build recipes/gippy
  - conda install gippy --use-local
#  - conda build recipes/pypotrace
#  - conda install pypotrace --use-local
script:
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - echo "TRAVIS_EVENT_TYPE=$TRAVIS_EVENT_TYPE"
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
      AGG_OUTPUT=$(conda build recipes/libagg --output);
      anaconda -v -t $CONDA_UPLOAD_TOKEN upload "$AGG_OUTPUT" -u coastline --force;
    fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
      GIPPY_OUTPUT=$(conda build recipes/gippy --output);
      anaconda -v -t $CONDA_UPLOAD_TOKEN upload "$GIPPY_OUTPUT" -u coastline --force;
    fi
#  - if [ "$TRAVIS_BRANCH" = "master" ]; then
#      PYPOTRACE_OUTPUT=$(conda build recipes/pypotrace --output);
#      anaconda -v -t $CONDA_UPLOAD_TOKEN upload "$PYPOTRACE_OUTPUT" -u coastline --force;
#    fi
