package:
  name: libagg
  version: 2.5.0
source:
  path: ../../vendor/agg-2.5
requirements:
  build:
    - gcc
    - libgfortran
about:
  home: http://antigrain.com/
  summary: "Anti-Grain Geometry (AGG) is a general purpose graphical toolkit written completely in standard and platform independent C++."
  license: GPL
