package:
  name: potrace
  version: 1.15
build:
  number: 0
  #skip: True # [osx]
source:
  fn: potrace-1.15.linux-x86_64.tar.gz
  url: http://potrace.sourceforge.net/download/1.15/potrace-1.15.tar.gz
requirements:
  build:
    - gcc   [linux]
  run:
test:
  commands:
    - "potrace --help"
about:
  home: http://potrace.sourceforge.net
  license: GPL
  summary: A tool for tracing a bitmap, which means, transforming a bitmap into a smooth, scalable image
