package:
  name: potrace
  version: 1.15
build:
  number: 0
  #skip: True # [osx]
source:
  fn: potrace_1.15_src_all.tar.gz
  url: https://depot.galaxyproject.org/software/potrace/potrace_1.15_src_all.tar.gz
requirements:
  build:
    - gcc   [linux]
  run:
test:
  commands:
    - "potrace --help"
about:
  home: http://potrace.sourceforge.net
  license: GPL
  summary: A tool for tracing a bitmap, which means, transforming a bitmap into a smooth, scalable image
