package:
  name: beachfront
  version: 0.2.4

source:
  path: ../../vendor/beachfront-py

requirements:
  build:
    - python 2.7.14
    - gippy 1.0.0.post1
    - pypotrace 0.1.3
    - requests 2.11.1
    - pyproj 1.9.5.1
  run:
    - python 2.7.14
    - gippy 1.0.0.post1
    - pypotrace 0.1.3
    - requests 2.11.1
    - pyproj 1.9.5.1

build:
  string: py{{py}}_0
  #binary_relocation: False

about:
  home: https://github.com/venicegeo/beachfront-py
  summary: "A library of functions used for the creation of vector shorelines automatically from imagery"
  license: Apache 2.0
