package:
  name: beachfront
  version: 0.1.0

source:
  path: ../../vendor/beachfront-py

requirements:
  build:
    - python 2.7.13
    - gippy 1.0.0
    - pypotrace 0.1.3
    - requests 2.11.1
    - fiona 1.7.4
    - pyproj 1.9.5.1
    - six 1.10.0
    - click
  run:
    - python 2.7.13
    - gippy 1.0.0
    - pypotrace 0.1.3
    - requests 2.11.1
    - fiona 1.7.4
    - pyproj 1.9.5.1
    - six 1.10.0

build:
  string: py{{py}}_0
  #binary_relocation: False

about:
  home: https://github.com/venicegeo/beachfront-py
  summary: "A library of functions used for the creation of vector shorelines automatically from imagery"
  license: Apache 2.0
