package:
  name: pzsvc-exec
  version: REPLACE_VERSION

source:
  path: ./pzsvc-exec

build:
  binary_relocation: False
  script_env:
   - GOROOT

about:
  home: https://github.com/venicegeo/pzsvc-exec
  summary: "Serve command-line programs to Piazza, based on the contents of a config file."
  license: Apache 2.0
