package:
  name: pzsvc-exec
  version: 2.0.2

source:
  git_url: https://github.com/venicegeo/pzsvc-exec.git

build:
  binary_relocation: False
  script_env:
   - GOROOT

about:
  home: https://github.com/venicegeo/pzsvc-exec
  summary: "Serve command-line programs to Piazza, based on the contents of a config file."
  license: Apache 2.0
