{% set version = "1.12.0" %}

{% set variant = "openblas" %}

package:
  name: numpy
  version: {{ version }}

source:
  path: ../../vendor/numpy

requirements:
  build:
    - toolchain
    - cython
    - python
    - setuptools
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*

test:
  requires:
    - nose
  commands:
    - f2py -h
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: http://numpy.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Array processing for numbers, strings, records, and objects.'

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
