package:
  name: pypotrace
  version: 0.1.3

source:
  # https://pypi.python.org/packages/28/6f/59ebf9fa50553426d28c0aec6d0690e84cca3841edd10276afaaedb8d02b/pypotrace-0.1.3.tar.gz 
  path: ../../vendor/pypotrace
requirements:
  build:
    - gcc
    - python 2.7.13
    - numpy 1.14.2
    - libagg
    - potrace
    #- fiona 1.6.3
  run:
    - python 2.7.13
    - numpy 1.14.2
    #- libpotrace 1.14.0
    #- libagg 2.5.0
    #- fiona 1.6.3

build:
  string: py{{py}}_0

about:
  home: https://github.com/flupke/pypotrace
  summary: "These bindings provide an object oriented API to the potrace library."
  license: GPL
