package:
  name: pypotrace
  version: 0.1.3

source:
  path: ../../vendor/pypotrace
requirements:
  build:
    - gcc
    - python
    - numpy 1.12.0
    - libagg
    - potrace
  run:
    - python
    - numpy 1.12.0

build:
  string: py{{py}}_0

about:
  home: https://github.com/flupke/pypotrace
  summary: "These bindings provide an object oriented API to the potrace library."
  license: GPL
