package:
  name: gippy
  version: 1.0.0

source:
  # https://github.com/gipit/gippy
  path: ../../vendor/gippy
requirements:
  build:
    - gcc
    - gdal 2.2.4
    - python 2.7.14
    - wheel

  run:
    - gdal 2.2.4 
    - python 2.7.14   

build:
  string: py{{py}}_0
  binary_relocation: False

about:
  home: https://github.com/gipit/gippy
  summary: "Gippy is a Python library for image processing of geospatial raster data"
  license: Apache 2.0
