package:
  name: beachfront
  version: 2.0.2

source:
  path: ./beachfront-py

requirements:
  build:
    - gippy 1.0.0.post3
    - pypotrace 0.1.3
    - requests 2.11.1
    - pyproj 1.9.5.1
    - python 2.7.13
  run:
    - gippy 1.0.0.post3
    - pypotrace 0.1.3
    - requests 2.11.1
    - pyproj 1.9.5.1
    - python 2.7.13

build:
  string: py{{py}}_0
  #binary_relocation: False

about:
  home: https://github.com/venicegeo/beachfront-py
  summary: "A library of functions used for the creation of vector shorelines automatically from imagery"
  license: Apache 2.0
